### ISSUE TITLE
Thank you for the theme

### ISSUE THREAD

**Issue by pjebs** [geoffmcnamara/newspaper-hugo-subtheme#1]
I really enjoyed your theme.

I was wondering however what I had to do to make the background look exactly like the original work.
In yours, you seem to have a "real newspaper" blotchy look whereas in the original, it is just a single color.

**Comment by geoffmcnamara** [comment]
I used a background image to give it the older look. It is just a matter of
taking the image out of the body style and sustitute the background color
of your choice.
Thanks for your interest in the project.
