### ISSUE TITLE
MIT

### ISSUE THREAD

**Issue by pjebs** [geoffmcnamara/newspaper-hugo-subtheme#2]
Is there a change you can relicense this as MIT?

**Comment by geoffmcnamara** [comment]
My intent was for it to be completely free. Have I missed something on that
regard. I partial to GNU licensing, is there a need for you to have it MIT?

**Comment by pjebs** [comment]
I can't really use it any projects due to license:

https://choosealicense.com/licenses/gpl-3.0/

**Comment by pjebs** [comment]
Anything I make using your theme must then be open sourced and also distributed under the same license. Then anyone who uses what I make has to do likewise.

**Comment by pjebs** [comment]
?

**Comment by geoffmcnamara** [comment]
I am not an expert or even well versed in the differences between licenses
but I am a strong proponent of open source. My hope is that anyone who
appreciates the work of others should likewise make their work openly
available in that same spirit as the work they incorporated into their
project. It appears that MIT licensing allows incorporation of other open
work into a project that might be at some point released as closed. This
breaks the spirit of open and total sharing. My apologies if this approach
seems severe or limiting.

**Comment by pjebs** [comment]
You can see the debacle caused by this license type here: https://blog.dgraph.io/post/relicensing-dgraph/

They eventually changed back to Apache due to backlash from potential customers.

**Comment by pjebs** [comment]
Also bear in mind that MIT is a very popular license for MIT - perhaps the most common.

**Comment by geoffmcnamara** [comment]
Changed license to MIT after some research after a request.

**Comment by geoffmcnamara** [comment]
I changed the license to MIT. Hope this helps.
Thanks for sharing your concerns and comments.

**Comment by pjebs** [comment]
Thank you
