### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by pjebs** [geoffmcnamara/newspaper-hugo-subtheme#4]
```
+-----layouts
|     +-----section # hugo uses this directory to find "section" specific "list" templates
|     |     +-----articles.html # hugo uses this template to combine postings into a newletter front page

```
In the readme, it mentions that there is a file in `layout/section/articles.html` but it does not appear to be in the repository.

What does that file do?

**Comment by geoffmcnamara** [comment]
That is just an optional file that you can add to further control listings
of articles - I don't use it so it was not included. I changed to the
README to hopefully better reflect that information.
I haven't played with this repository in quite a while but with a lot of
work, you might be able to use that listing in a table of contents and
somehow add it to the "front page" of the newspaper. But, again, that would
be a lot of work. Let me know if this helps you and I am not even sure if
it is possible or how to make that work.
Hope this provides a little "better" information on the optional file
article.html. The README was unfortunately misleading - you have my
apologies.

**Comment by pjebs** [comment]
If I want to make the "newspaper" page appear in the homepage rather than under the articles section, how would I achieve that?

**Comment by geoffmcnamara** [comment]
relatively simple to get started...
cd (where you downloaded or copied the project)
mkdir layouts/_default


# make sure you have the config.toml file in the base of that dir
# minimally you need:
baseURL = "http://example.org/"
languageCode = "en-us"
Title = "My New Hugo Site"
##############

cp layouts/articles/list.html layouts/_default
hugo -v server

Enjoy!

**Comment by pjebs** [comment]
Thanks for the theme

**Comment by geoffmcnamara** [comment]
You are welcome.
Enjoy!

**Comment by geoffmcnamara** [comment]
Hey,

I just signed the petition "City of Elizabeth City: Removal of all
confederate statues." and wanted to see if you could help by adding your
name.

Our goal is to reach 2,500 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/pKYGmt7YKL

Thanks!
Geoff
